export const ACTION = {
    GET_PROJECTS: 'TODO/GET_PROJECTS',
    POST_PROJECTS: 'TODO/POST_PROJECTS',
    LOGIN: 'TODO/LOGIN',
    SHOW_LOGOUT: 'TODO/SHOW_LOGOUT',
    ADDED_EMAIL: 'TODO/ADDED_EMAIL'
};