export const ACTION = {
    GET_TABS: 'YOURTABS/GET_TABS',
    POST_TAB: 'YOURTABS/POST_TAB',
    POST_HEAD: 'YOURTABS/POST_HEAD',
    SEARCH_TABS: 'YOURTABS/SEARCH_TABS',
    GET_VIEW_TABS: 'YOURTABS/GET_VIEW_TABS',
    CHANGE_EDIT: 'YOURTABS/CHANGE_EDIT',
    EDIT_TAB: 'YOURTABS/EDIT_TAB',
    DELETE_TAB: 'YOURTABS/DELETE_TAB',
    CHANGE_LOGGEDIN: 'YOURTABS/CHANGE_LOGGEDIN'
};